# Generated by Django 4.2 on 2023-04-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_doc', models.CharField(max_length=255)),
                ('documento', models.PositiveSmallIntegerField()),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
